// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductStoreMVC.Data;

// Այս attribute-ը ցույց է տալիս,
// որ snapshot-ը կապված է AppDbContext-ի հետ։
[DbContext(typeof(AppDbContext))]

// partial նշանակում է,
// որ class-ը կարող է բաժանված լինել մի քանի file-երի մեջ։
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    // BuildModel() մեթոդը նկարագրում է
    // ամբողջ database model-ի ներկայիս վիճակը։
    protected override void BuildModel(ModelBuilder modelBuilder)
    {

#pragma warning disable 612, 618

        // EF Core metadata/configuration
        // ProductVersion -> EF Core-ի տարբերակ
        // MaxIdentifierLength -> SQL object name-ի max երկարություն
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        // SQL Server-ում Identity columns-ի օգտագործում
        // (auto increment columns)
        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // Category entity-ի configuration
        modelBuilder.Entity("ProductStoreMVC.Models.Category", b =>
        {

            // Id property configuration
            b.Property<int>("Id")

                // Auto Increment
                .ValueGeneratedOnAdd()

                // SQL type = int
                .HasColumnType("int");

            // SQL Server Identity(1,1)
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            // Name property configuration
            b.Property<string>("Name")

                // NOT NULL
                .IsRequired()

                // SQL type
                .HasColumnType("nvarchar(max)");

            // Primary Key
            b.HasKey("Id");

            // SQL table name
            b.ToTable("Categories");
        });

        // Product entity-ի configuration
        modelBuilder.Entity("ProductStoreMVC.Models.Product", b =>
        {

            // Primary Key column
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            // Identity(1,1)
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            // Foreign Key column
            b.Property<int>("CategoryId")
                .HasColumnType("int");

            // Product Name
            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            // Product Price
            b.Property<decimal>("Price")

                // decimal(18,2)
                .HasColumnType("decimal(18,2)");

            // Primary Key
            b.HasKey("Id");

            // Index CategoryId-ի վրա
            // Արագացնում է JOIN/SEARCH queries
            b.HasIndex("CategoryId");

            // SQL table name
            b.ToTable("Products");
        });

        // Relationship configuration
        modelBuilder.Entity("ProductStoreMVC.Models.Product", b =>
        {

            // Product has one Category
            b.HasOne("ProductStoreMVC.Models.Category", "Category")

                // Category can have many Products
                .WithMany()

                // Foreign Key
                .HasForeignKey("CategoryId")

                // Cascade Delete
                .OnDelete(DeleteBehavior.Cascade)

                // Required relationship
                .IsRequired();

            // Navigation Property
            b.Navigation("Category");
        });

#pragma warning restore 612, 618
    }
}
